version: "3"

services:
  flask:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: flask-api
    working_dir: /var/www
    ports:
      - 5000:5000
    volumes:
      - ./:/var/www
    tty: true
  db:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_ROOT_PASSWORD: mysql
      DB_NAME: flask_todo
